/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as DataDictionaryRouteImport } from './routes/data-dictionary'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardSummaryRouteImport } from './routes/dashboard.summary'
import { Route as DashboardChartsRouteImport } from './routes/dashboard.charts'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDictionaryRoute = DataDictionaryRouteImport.update({
  id: '/data-dictionary',
  path: '/data-dictionary',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSummaryRoute = DashboardSummaryRouteImport.update({
  id: '/dashboard/summary',
  path: '/dashboard/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardChartsRoute = DashboardChartsRouteImport.update({
  id: '/dashboard/charts',
  path: '/dashboard/charts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/data-dictionary': typeof DataDictionaryRoute
  '/projects': typeof ProjectsRoute
  '/dashboard/charts': typeof DashboardChartsRoute
  '/dashboard/summary': typeof DashboardSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/data-dictionary': typeof DataDictionaryRoute
  '/projects': typeof ProjectsRoute
  '/dashboard/charts': typeof DashboardChartsRoute
  '/dashboard/summary': typeof DashboardSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/data-dictionary': typeof DataDictionaryRoute
  '/projects': typeof ProjectsRoute
  '/dashboard/charts': typeof DashboardChartsRoute
  '/dashboard/summary': typeof DashboardSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/data-dictionary'
    | '/projects'
    | '/dashboard/charts'
    | '/dashboard/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/data-dictionary'
    | '/projects'
    | '/dashboard/charts'
    | '/dashboard/summary'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/data-dictionary'
    | '/projects'
    | '/dashboard/charts'
    | '/dashboard/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  DataDictionaryRoute: typeof DataDictionaryRoute
  ProjectsRoute: typeof ProjectsRoute
  DashboardChartsRoute: typeof DashboardChartsRoute
  DashboardSummaryRoute: typeof DashboardSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-dictionary': {
      id: '/data-dictionary'
      path: '/data-dictionary'
      fullPath: '/data-dictionary'
      preLoaderRoute: typeof DataDictionaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/summary': {
      id: '/dashboard/summary'
      path: '/dashboard/summary'
      fullPath: '/dashboard/summary'
      preLoaderRoute: typeof DashboardSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/charts': {
      id: '/dashboard/charts'
      path: '/dashboard/charts'
      fullPath: '/dashboard/charts'
      preLoaderRoute: typeof DashboardChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  DataDictionaryRoute: DataDictionaryRoute,
  ProjectsRoute: ProjectsRoute,
  DashboardChartsRoute: DashboardChartsRoute,
  DashboardSummaryRoute: DashboardSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
